In [22]:
import sqlite3
import pandas as pd
import os
conn = sqlite3.connect('mailchimp.db')
cursor = conn.cursor()

In [23]:
query ="""
SELECT * 
FROM CONTACT_LIST 
WHERE TAG IS NULL 
    AND PHONE IS NOT NULL
LIMIT 1500
"""
print(query)

SELECT *
FROM CONTACT_LIST
WHERE TAG IS NULL
    AND PHONE IS NOT NULL
LIMIT 1500

In [24]:
#sqalchemy query execution
top = pd.read_sql_query(query, conn)
top.head()

,UID,FULL_NAME,FIRST_NAME,LAST_NAME,COMPANY,EMAIL,PHONE,TAG,COMPANY_SIZE,BOUNCED,MAILCHIMP_IMPORT,CLICKUP_IMPORT
0,2,AALIYAH HAZARI KHAN,AALIYAH,KHAN,F A M REAL ESTATE BROKER L.L.C (BRANCH),aaliyah@famproperties.com,42775516,None,139,live,None,None
1,7,AAMIR RAZA MUHAMMAD AKARM,AAMIR,AKARM,CIVIL ARCH REAL ESTATE BROKERS,aranjha333@gmail.com,43713401,None,1,live,None,None
2,9,AARON KEITH PARTON,AARON,PARTON,DACHA REAL ESTATE,aaron@dacha.ae,97126666576,None,52,live,None,None
3,10,AARON NILE DUNBAR,AARON,DUNBAR,HOUSE HUNTERS REAL ESTATE BROKERS L.L.C,aaron@househuntersdubai.com,504100149,None,27,live,None,None
4,14,AARTI DEVGUN SHARMA,AARTI,SHARMA,ONE STOP REALTY REAL ESTATE,aarti.devgun@gmail.com,544303555,None,3,live,None,None

In [25]:
#CONVERT THE EMAIL COLUMN INTO A STRING TO SQL PROCESSING
email_list = top['EMAIL']
email_string= '('
for i in range(len(email_list)):
    if i < len(email_list)-1:
        email_string = email_string + f"'{email_list[i]}',"
    else:
        email_string = email_string + f"'{email_list[i]}'"
email_string= email_string + ")"
print(email_string[:1000])

('aaliyah@famproperties.com','aranjha333@gmail.com','aaron@dacha.ae','aaron@househuntersdubai.com','aarti.devgun@gmail.com','asim@textureproperties.com','aasim.rady@timi.ae','yomi@outlookproperties.ae','abbas@homes4udubai.ae','mr.rje2020@gmail.com','abbas@moodproperties.com','abbasaliu@asteco.net','abbey@allsoppandallsopp.com','drsafra@gmail.com','abdallah@famproperties.com','abdallahelhadidy1@gmail.com','watanq@hotmail.com','abdul.b@landsterling.com','abdelila@famproperties.com','aziz@firsthomesdubai.com','abdelhady.elhady@gmail.com','abaid@tabanirealestate.ae','houseandhome@ctcdubai.com','sales3@psidubai.com','abdukodir.yokubov@engelvoelkers.com','abdul@hausandhaus.com','arsalagroup@live.com','jaleel@almirath.ae','jaleellandcom@gmail.com','ak@rrealestate.ae','karim@providentstate.com','abdul.majeed@h4l.ae','moizworld@hotmail.com','abdul@vre.ae','abdullrhman064@gmail.com','abdul.rahman@maplenrose.com','raza@seapanther.ae','raziabdul4@gmail.com','abdul@seapanther.ae','ar@tcre.ae','saje

In [26]:
#VALIDATION SQL THAT USES THE EMAIL_STRING SQL TO VERIFY UPDATES
filter = pd.read_sql_query(f"SELECT * FROM CONTACT_LIST WHERE EMAIL IN {email_string} limit 10", conn)
filter

,UID,FULL_NAME,FIRST_NAME,LAST_NAME,COMPANY,EMAIL,PHONE,TAG,COMPANY_SIZE,BOUNCED,MAILCHIMP_IMPORT,CLICKUP_IMPORT
0,2,AALIYAH HAZARI KHAN,AALIYAH,KHAN,F A M REAL ESTATE BROKER L.L.C (BRANCH),aaliyah@famproperties.com,42775516,None,139,live,None,None
1,7,AAMIR RAZA MUHAMMAD AKARM,AAMIR,AKARM,CIVIL ARCH REAL ESTATE BROKERS,aranjha333@gmail.com,43713401,None,1,live,None,None
2,9,AARON KEITH PARTON,AARON,PARTON,DACHA REAL ESTATE,aaron@dacha.ae,97126666576,None,52,live,None,None
3,10,AARON NILE DUNBAR,AARON,DUNBAR,HOUSE HUNTERS REAL ESTATE BROKERS L.L.C,aaron@househuntersdubai.com,504100149,None,27,live,None,None
4,14,AARTI DEVGUN SHARMA,AARTI,SHARMA,ONE STOP REALTY REAL ESTATE,aarti.devgun@gmail.com,544303555,None,3,live,None,None
5,15,AASIM AMINUDDIN AMIN UDDIN SHEIKASON,AASIM,SHEIKASON,TEXTURE PROPERTIES L.L.C,asim@textureproperties.com,45897927,None,14,live,None,None
6,16,AASIM RADY ELSAID MOHAMMED HASSANIEN,AASIM,HASSANIEN,TIMI PROPERTY,aasim.rady@timi.ae,44528859,None,5,live,None,None
7,18,ABAYOMI FESTUS IDOWU,ABAYOMI,IDOWU,OUTLOOK PROPERTIES,yomi@outlookproperties.ae,504100149,None,4,live,None,None
8,19,ABBAS ALA HAMID,ABBAS,HAMID,HOMES 4 U REAL ESTATE BROKER,abbas@homes4udubai.ae,0,None,3,live,None,None
9,21,ABBAS MORTEZAGHOLI RAJAEI,ABBAS,RAJAEI,MARAMES REAL ESTATE BROKERS,mr.rje2020@gmail.com,0,None,1,live,None,None

In [27]:
#CONVERT THE EMAIL_LIST INTO A LIST OF TUPLES FOR EXECUTION BY EXECUTMANY METHOD
stmt = [(i,) for i in email_list]
print(stmt[:10])

[('aaliyah@famproperties.com',), ('aranjha333@gmail.com',), ('aaron@dacha.ae',), ('aaron@househuntersdubai.com',), ('aarti.devgun@gmail.com',), ('asim@textureproperties.com',), ('aasim.rady@timi.ae',), ('yomi@outlookproperties.ae',), ('abbas@homes4udubai.ae',), ('mr.rje2020@gmail.com',)]

In [28]:
#SET TAG 
TAG = 'JAN_25'

In [29]:
#EXECTUMANY
cursor.executemany(f"UPDATE CONTACT_LIST SET TAG = '{TAG}', MAILCHIMP_IMPORT='Y' WHERE EMAIL = ?",stmt)
conn.commit()

In [30]:
#VALIDATION SQL THAT USES THE EMAIL_STRING SQL TO VERIFY UPDATES
filter = pd.read_sql_query(f"SELECT * FROM CONTACT_LIST WHERE EMAIL IN {email_string} limit 10", conn)
filter

,UID,FULL_NAME,FIRST_NAME,LAST_NAME,COMPANY,EMAIL,PHONE,TAG,COMPANY_SIZE,BOUNCED,MAILCHIMP_IMPORT,CLICKUP_IMPORT
0,2,AALIYAH HAZARI KHAN,AALIYAH,KHAN,F A M REAL ESTATE BROKER L.L.C (BRANCH),aaliyah@famproperties.com,42775516,JAN_25,139,live,Y,None
1,7,AAMIR RAZA MUHAMMAD AKARM,AAMIR,AKARM,CIVIL ARCH REAL ESTATE BROKERS,aranjha333@gmail.com,43713401,JAN_25,1,live,Y,None
2,9,AARON KEITH PARTON,AARON,PARTON,DACHA REAL ESTATE,aaron@dacha.ae,97126666576,JAN_25,52,live,Y,None
3,10,AARON NILE DUNBAR,AARON,DUNBAR,HOUSE HUNTERS REAL ESTATE BROKERS L.L.C,aaron@househuntersdubai.com,504100149,JAN_25,27,live,Y,None
4,14,AARTI DEVGUN SHARMA,AARTI,SHARMA,ONE STOP REALTY REAL ESTATE,aarti.devgun@gmail.com,544303555,JAN_25,3,live,Y,None
5,15,AASIM AMINUDDIN AMIN UDDIN SHEIKASON,AASIM,SHEIKASON,TEXTURE PROPERTIES L.L.C,asim@textureproperties.com,45897927,JAN_25,14,live,Y,None
6,16,AASIM RADY ELSAID MOHAMMED HASSANIEN,AASIM,HASSANIEN,TIMI PROPERTY,aasim.rady@timi.ae,44528859,JAN_25,5,live,Y,None
7,18,ABAYOMI FESTUS IDOWU,ABAYOMI,IDOWU,OUTLOOK PROPERTIES,yomi@outlookproperties.ae,504100149,JAN_25,4,live,Y,None
8,19,ABBAS ALA HAMID,ABBAS,HAMID,HOMES 4 U REAL ESTATE BROKER,abbas@homes4udubai.ae,0,JAN_25,3,live,Y,None
9,21,ABBAS MORTEZAGHOLI RAJAEI,ABBAS,RAJAEI,MARAMES REAL ESTATE BROKERS,mr.rje2020@gmail.com,0,JAN_25,1,live,Y,None

In [31]:
#pull contacts that were updated
contacts = pd.read_sql_query(f"SELECT * FROM CONTACT_LIST WHERE EMAIL IN {email_string}", conn)
contacts.head()

,UID,FULL_NAME,FIRST_NAME,LAST_NAME,COMPANY,EMAIL,PHONE,TAG,COMPANY_SIZE,BOUNCED,MAILCHIMP_IMPORT,CLICKUP_IMPORT
0,2,AALIYAH HAZARI KHAN,AALIYAH,KHAN,F A M REAL ESTATE BROKER L.L.C (BRANCH),aaliyah@famproperties.com,42775516,JAN_25,139,live,Y,None
1,7,AAMIR RAZA MUHAMMAD AKARM,AAMIR,AKARM,CIVIL ARCH REAL ESTATE BROKERS,aranjha333@gmail.com,43713401,JAN_25,1,live,Y,None
2,9,AARON KEITH PARTON,AARON,PARTON,DACHA REAL ESTATE,aaron@dacha.ae,97126666576,JAN_25,52,live,Y,None
3,10,AARON NILE DUNBAR,AARON,DUNBAR,HOUSE HUNTERS REAL ESTATE BROKERS L.L.C,aaron@househuntersdubai.com,504100149,JAN_25,27,live,Y,None
4,14,AARTI DEVGUN SHARMA,AARTI,SHARMA,ONE STOP REALTY REAL ESTATE,aarti.devgun@gmail.com,544303555,JAN_25,3,live,Y,None

In [34]:
#send to csv
contacts.to_csv(path_or_buf=os.getcwd()+'/db_to_mailchimp.csv')

In [35]:
cursor.close()